version: '3'

services:
  nginx-react:
    # Bật tương tác với container thông qua terminal host.
    stdin_open: true
    container_name: workshop_reactjs
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules